### ISSUE TITLE
Add accumulative height to statistics graph

### ISSUE THREAD

**Issue by olevi70** [IsraelHikingMap/Site#692]
## What I expect to happen
add to track height graph point info, the accumulated height to  that track point and not only absolute point height.

## What really happened
the info provided for each point is: distance, point height and climb degree

**Comment by HarelM** [comment]
Can you please explain why this is needed? 
What is the user scenario this is intended to solve? 
Is it relevant only to bike riders?
While planning the route accumulative data is presented in the right lower corner, does this cover your needs?

**Comment by olevi70** [comment]
I believe this item (and #693) relevant for bike riders only.
for a start items 692 & 693 are orthogonal, I see no real reason to implement both. If i had to choose i would prefer item 692 over 693.
It is useful for planning a new route but more important for reviewing (studding) existing routes, with emphasis to long distance routes (above 100K/bike-packing)
it helps to identify the slow and hard parts of the track, planning rests, estimate time and have rough estimation for each day ride.
cutting and merging tool is sort of solution, but its not flexible and easy to use as a simple field data.
today i use LocusMap app for this purpose.

same goes for planning new route. it is easier to review the route once its ready than trying to keep track at each point of its accumulative height.

**Comment by HarelM** [comment]
Not sure what you mean by the following sentence (what purpose are you talking about? is it a site or a mobile app?):
>today i use LocusMap app for this purpose.

In general, I'm not sure how this is useful to most users so I'm not eager to add it to the UI as it will only clutter things.
If we are talking about a 100Km route than showing accumulative data from the route start won't help much if I understand the use case as you probably want to know the accumulative height from the day's start, wouldn't you?
I tend to think that #693, while might be more complex to implement, can prove a better user experience and will not affect the regular user who might not have a need for this feature as it will only work when selecting a part of the graph.

**Comment by HarelM** [comment]
@valleyofdawn any inputs on this would help as I know you wanted something similar in the past.

**Comment by valleyofdawn** [comment]
This is the same accumulative calculation we have in the total route stats. Would be useful to cyclists. Not sure if it's worth the extra clutter.

**Comment by olevi70** [comment]
1. LocusMap app - once track is ready (or using existing track) i load it to Locus Map navigation app, which allow me to review various info including accumulative height at each point of the track
2. once the accumulative height is available at each point its easy to calculate the diff between any two point of track (simple subtraction), its flexible and easy to use
3. as i said 692&693 are orthogonal, both serves same need (for me anyway)

**Comment by HarelM** [comment]
I'm thinking about implementing the above thought similar to how it looks here:
https://giscience.github.io/Leaflet.Heightgraph/
To be more specific: only the mouse drag over the chart in order to select the relevant area, once selected a box with the data will be presented, or the data will be updated in the lower part of the chart, haven't decided yet.
No zooming to the relevant part of the route (god knows why this is the behavior they chose to implement) and no chart by type of land as it will create what I believe is unnecessary clutter.
So only drag selection.
This won't create clutter to any one who doesn't need this and will solve both issues (#692, #693).

**Comment by HarelM** [comment]
Here's the proposed solution:
Regular chart:
![image](https://user-images.githubusercontent.com/3269297/39962049-be715c00-564c-11e8-92ba-127b73a7d8d2.png)
<kbd>Click</kbd>+<kbd>Drag</kbd> on the chart to create a selection of a sub route.
While the selection is made the statistics at the bottom change continuously, tooltip is visible and the map shows the current location of the selection end.
![image](https://user-images.githubusercontent.com/3269297/39962083-87fef5f0-564d-11e8-95dd-1af3b02a7ee1.png)
To disable selection click anywhere on the chart/close it/enlarge it.
Let me know if this covers this issue and #693.
If so I'll commit the changes and make it available in the next release.

**Comment by valleyofdawn** [comment]
It does covet the issue. Maybe  גובה מצטבר ושיפוע ממוצע. Can you think of a way to make it discoverable? Did they ask for deccent as well?

**Comment by HarelM** [comment]
>Maybe גובה מצטבר ושיפוע ממוצע.

Not sure what you mean - I haven't changed tooltips, although I now see that they are missing when the chart is open. I'm not planning on changing the text as I think it's OK as it is now.
>  Can you think of a way to make it discoverable?

I don't have a good idea, but this is an advanced feature that I don't mind if most users will not be aware of it.

> Did they ask for deccent as well?

You can read both issues, I don't see a request, never the less I've implemented it to be consistent with what's currently available.

**Comment by olevi70** [comment]
if I may few points:
1. usage and information-wise, this is perfect
2. As i see it descent is less important but be glad to have it. 
3. I assume the "traveling point" marking the track point as mouse moves on graph will still exist in this case.

thanks a lot for the effort, I appreciate it.

**Comment by valleyofdawn** [comment]
Oh, I got it wrong, I thought the tooltip gave the info on the section.
Good then.

**Comment by HarelM** [comment]
This has an issue when dragging while using Firefox.
