### ISSUE TITLE
Site becomes slow when mileage markers are on and zoom level is changed

### ISSUE THREAD

**Issue by oriori** [IsraelHikingMap/Site#945]
## What I expect to happen
Site to remain responsive

## What really happened
Site becomes slow

## What I did that caused the issue - step by step
Load the route https://israelhiking.osm.org.il/share/nRneknM0RJ
Turn mileage markers on.
Zoom in and out repeatedly

## My environment
* Operating System and version:
Win 10

* Web Browser and version:
Chrome
## Thing I think the developers should know, images, links etc.
Might be related to the length of the trail.

**Comment by HarelM** [comment]
Thanks for reporting. I'm not sure there's much to do here since this is an extreme case.
Has this worked better in the previous site?

**Comment by oriori** [comment]
Yes, I think so.

**Comment by HarelM** [comment]
This is how the above example was looking in previous version, I doubt it's useful:
![image](https://user-images.githubusercontent.com/3269297/51802134-6d1eb300-224f-11e9-8b90-3c18d33fc75a.png)
I'll keep this issue open for profiling sake and see if I can improve the performance, but I'm not positive...

**Comment by EitanBusheri** [comment]
I feel something very similar.
For me it has nothing to do with the route length.
My feeling is that there is a code in loop that eventually Chrome ask to kill the page.

**Comment by HarelM** [comment]
@EitanBusheri can you share an example that causes this? Or maybe steps to reproduce the issue?

**Comment by amiad** [comment]
The site is slow me too. The tiles loading slowly. Before the upgrade they loaded immediately.
Firefox 66.0b4 on Arch Linux.

**Comment by valleyofdawn** [comment]
I'm not experiencing general slowness, but with the mileage markers on, rendering does become sluggish.
It's obvious when you have a long track with markers and you zoom in and out on it. 
It's pretty fast when the mileage markers are turned off.

**Comment by HarelM** [comment]
Mileage merkers are recalculated every time you zoom in and out do to a request to make it zoom dependant.
the calculation is done by iterating over all the points and finding the right location to place the markers.
Longer track will have longer calculation time, I don't see a way to avoid this.
If the sluggishness annoys you - turn off the markers and turn them on only when needed...

**Comment by HarelM** [comment]
Can you guys test this in the new beta site? I hope this is resolved...

**Comment by oriori** [comment]
Mileage markers aren't displayed at all for me. 
Any route, try to turn mileage markers on from the altitude profile window.
Window 10, Chrome.

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/57009382-e89d5100-6bfe-11e9-8378-e437539f440c.png)

**Comment by valleyofdawn** [comment]
I don't experience a slowdown with long routes and extensive zooming

**Comment by oriori** [comment]
I tried from another computer and still can't get the markers to show up. Win 10 , chrome as well. Tried with Microsoft Edge and there I can't even draw a new route. Probably a browser fault not because of the new version.

**Comment by HarelM** [comment]
@oriori can you please take a screen shot of the entire screen after doing the following:
1. Create a route that is more than 5 KM
2. Open the statistics chart (bottom right)
3. Click the drop icon on the left of the chart to show KM-markers
4. Click F-12
Thanks

**Comment by oriori** [comment]
[image: image.png]

**Comment by HarelM** [comment]
Can you switch to the console tab on the right? Seems like there are errors.
Can you also check if ctrl+F5 to remove chance cache helps?

**Comment by oriori** [comment]
I get the message "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT"
many times. It's because of the adBlock chrome plugin. If I turn it off the
markers appear (after I reload the site). With the adBlock on, the markers
don't appear.
This happens only in the beta version.

**Comment by HarelM** [comment]
I have no clue as to why this would happen. But in any case it is not related to this issue...
Please let me know if you encounter slowness, if not please close this bug. Feel free to open a different one about adblock.

**Comment by oriori** [comment]
Works fine when AdBlock is disabled.
